import type { NextPage } from 'next'
import Head from 'next/head'
import Router from 'next/router'
import { useContext } from 'react'
import { UserContext } from '../contexts/UserContext'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  const { user } = useContext(UserContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Username: {user?.username}</p>
        <p>Email: {user?.email}</p>
      </main>
    </div>
  )
}

export default Home
